

CREATE OR REPLACE   VIEW ASSCLIENTEUSUARIO AS
SELECT
	 OCRD."CardCode"  AS "IDCLIENTEERP",
	 "IDUSUARIOERP" AS "IDUSUARIOERP" 
FROM OCRD INNER JOIN USUARIO ON  OCRD."SlpCode" = USUARIO."IDUSUARIOERP"
WHERE OCRD."CardType" = 'C'

UNION 

SELECT 
C."CardCode" AS "IDCLIENTEERP" ,
rr."U_CodVendedor" AS "IDUSUARIOERP"  
FROM "@RO_REPRESENTANTE" rr 
INNER JOIN OSLP V ON rr."Code"  = V."U_CodRepresentante" 
INNER JOIN OCRD C ON V."SlpCode" = C."SlpCode"  
WHERE V."U_Integracao_sovis" = 1




